config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :developers, only: [:create, :show, :new, :index] do
    resources :offers, only: [:create, :new]
  end

  resources :projects, only: [:create, :show, :new] do
    resources :offers, only: [:index]
  end

  resources :offers, only: [:update]
  
  resources :chatrooms, only: [:show, :create] do
    resources :messages, only: :create
  end
  
  get "my_dev_profile", to: "developers#my_dev_profile", as: :my_dev_profile
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
  def new
    @developer = DeveloperProfile.new
  end

  def my_dev_profile
    @dev_profile = current_user.developer_profile
    @chatroom = Chatroom.last
    @offers = @dev_profile.offers
  end

  def show
    @developer = DeveloperProfile.find(params[:id])
    @dev_technologies = @developer.technologies
    @dev_languages = @developer.spoken_languages.first
    @dev_pic = @developer.avatar
    # Here is where I want to create a chatroom if one does not exist
    @existing_chatroom = Chatroom.between(current_user, @developer.user)
  end


  def create
    @developer = DeveloperProfile.new(developer_params)
    @developer.user = current_user

    if @developer.save
       redirect_to developer_path(@developer)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @developers = developer.all
  end

  def developer_pic
    @developers.all
  end 

  private

  def developer_params
    params.require(:developer).permit(:years_of_experience, :school, :degree)
  end
end

app/views/developers/my_dev_profile.html.erb
<main>
  <h1>Dev Dashboards</h1>
  <ul>
    <% @offers.each do |offer| %>
      <li>
        <p><%= offer.project.name %></p>
        <p><%= offer.status %></p>
        <%# Use simpleform to update the state of the status variable %>
        <%= simple_form_for offer do |f| %>
          <%= f.input :status, collection: ["pending", "accepted", "rejected"] %>
          <%= f.submit "Update" %>
        <% end %>
      </li>
    <% end %>
  </ul>
  <%= button_to "Open Chat", chatroom_path(@chatroom), method: :get %>
</main>

<style>
  main {
  	display: grid;
  	place-content: center
  }
</style>

app/views/developers/new.html.erb
<section>
  <h1>Create your developer profile  </h1>
  <main class="form-wrapper">
    <%= simple_form_for(@developer, url: developers_path) do |f| %>
      <%= f.input :school %>
      <%= f.input :degree, as: :text %>
      <%= f.input :technology, as: :string %>
      <%= f.input :years_of_experiance, as: :decimal %>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
      <%= f.submit class: "form-btn"  %>
    <% end %>
  </main>
</section>

app/views/developers/show.html.erb
<main class="profile-page--wrapper">
  <div class="card dev-profile--info-wrapper">
    <div class="dev-profile--info-container">
      <div class="gradiented-card-cover">
      </div>
      <img src="<%= @dev_pic %>" alt="A american portrait of a developer" class="avatar-img mt-20">
      <h1 class="dev-profile--title">
        <%= @developer.user.first_name %> <%= @developer.user.last_name %>
      </h1>
      <span> <%= @developer.description %></span>
      <p class="dev-profile--sm-subtitle"> Speaks <%= @dev_languages.name %></p>
    </div>
    <div class="dev-profile--btn-container">
      <% unless current_user == @user %>
        <% if @existing_chatroom.nil? %>
          <%= button_to "Open Chat", chatrooms_path, method: :post,  params: { developer_id: @developer.id } %>
        <% else %>
          <%= button_to "Start Chat", chatroom_path(@existing_chatroom), method: :get %>
        <% end %>
      <% end %>
      <%= button_to "Make an offer", new_developer_offer_path(@developer), method: :get %>
    </div>
  </div>
  <div class="card dev-profile--summary-wrapper">
    <h2 class="card-label">Summary</h2>
    <p><%= @developer.bio %></p>
  </div>
  <div class="card dev-profile--expertise-wrapper">
    <h2 class="card-label">Expertise</h2>
    <div class="inline-flex">
      <% @dev_technologies.each do |tech| %>
        <span class="dev-profile--tech"> <%= tech.name %></span>
      <% end %>
    </div>
  </div>
  <div class="card dev-profile--education-wrapper">
    <h2 class="card-label">Education</h2>
    <span class="dev-profile--subtitle text--is-primary"> <%= @developer.school %></span>
    <span class="dev-profile--subtitle"> <%= @developer.degree %></span>
  </div>
</main>
<style>
  .profile-page--wrapper {
    padding: 60px 24px 0px 24px;
  }
  .dev-profile--info-wrapper {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    background-color: var(--primary-container);
    border-radius: 8px;
    padding-bottom: 8px !important;
  }
  .dev-profile--subtitle {
    font-weight: 400;
  }
  .dev-profile--sm-subtitle {
    font-weight: 400;
    font-size: 12px;
  }

  .dev-profile--btn-container {
    width: 100%;
    display: flex;
    justify-content: space-between;
    gap: 8px
  }
  .dev-profile--btn-container  > * {
    flex-grow: 1;
  }
   .dev-profile--btn-container  > * > * {
    width: 100%;
  }
  .inline-flex {
    display: flex;
    align-items: center;
    justify-content: space-around;
  }
  .dev-profile--tech {
    font-weight: 600;
    font-size: 20px;
    color: var(--txt-secondary);
    flex-grow: 1;
    text-align: center;
    padding: 20px 0;
  }
  .dev-profile--tech:nth-of-type(odd) {
    border-right: 1px solid rgba(18, 18, 18, 0.12);;
  }
  .text--is-primary {
    font-size: 20px;
    font-weight: 500;
    line-height: 120%;
    color: var(--txt-secondary);
  }
</style>