config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :developers, only: [:create, :show, :new, :index] do
    resources :offers, only: [:create, :new]
  end

  resources :projects, only: [:create, :show, :new] do
    resources :offers, only: [:index]
  end

  resources :offers, only: [:update]
  
  resources :chatrooms, only: [:show, :create] do
    resources :messages, only: :create
  end
  
  get "my_dev_profile", to: "developers#my_dev_profile", as: :my_dev_profile
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar--wrapper">
  <%= link_to root_path, class: "logo" do %>
    <%= image_tag "startapp-logo--w-bg.svg", class: "logo" %>
  <% end %>
  <div class="navbar--float-right--container">
    <% if user_signed_in? %>
      <% if current_user.founder? %>
        <% unless current_user.projects.last.nil? %>
          <%= link_to "Projects", project_path(current_user.projects.last), class: "nav-link" %>
          <% unless current_user.projects.last.offers.empty? %>
            <%= link_to "Offers",  project_offers_path(current_user.projects.last), class: "nav-link" %>
          <% end %>
        <% end %>
        <% unless current_user.founder_chatrooms.last.nil?%>
          <%= link_to "Inbox", chatroom_path(current_user.founder_chatrooms.last), class: "nav-link" %>
        <% end %>
      <% else current_user.developer? %>
        <%= link_to "click here !!!", my_dev_profile_path  %>
      <% end %>
      <%# HERE is the link to redirest to the developer dashboards %>
      <%# <%= link_to "My developer profile", my_dev_profile_path %>
      <%= image_tag "", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
        <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
      </div>
    <% else %>
      <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      <%= link_to "Get started", new_user_registration_path %>
    <% end %>
  </div>
</div>
<style>
  .logo {
    width: 40px;
    font-weight: 600;
    text-decoration: none;
    color: var(--on-primary);
  }
  .navbar--wrapper {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 16px 20px;
  }
  .navbar--float-right--container {
    display: flex;
    align-items: center;
    gap: 10px
  }
  /* .navbar--float-right--container > :nth-child(2 of .nav-link) {
    margin: 0 10px;
  } */
  .navbar--float-right--container > .nav-link:last-of-type {
    background-color: var(--secondary-container);
    color: var(--on-secondary);
    padding: 12px 16px;
    border-radius: 4px;
  }

  .dropdown-toggle {
    display: none;
  }
</style>