config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :developers, only: [:create, :show, :new, :index] do
    resources :offers, only: [:create, :new]
  end

  resources :projects, only: [:create, :show, :new] do
    resources :offers, only: [:index]
  end

  resources :offers, only: [:update]
  
  resources :chatrooms, only: [:show, :create] do
    resources :messages, only: :create
  end
  
  get "my_dev_profile", to: "developers#my_dev_profile", as: :my_dev_profile
end

app/models/project.rb
class Project < ApplicationRecord
  INDUSTRY = ["Social Media", "Home Services", "Food & Beverage", "E-learning", "E-commerce", "Fitness", "Consulting", "Music & Entertainment"];
  belongs_to :user
  belongs_to :spoken_language, optional: true
  has_many :project_technologies
  has_many :technologies, through: :project_technologies
  has_many :offers
  has_many :top_picks
  SPOKEN_LANGUAGE = ["English", "French", "Spanish", "German", "Arabic", "Portuguese", "Mandarin"]
  TECHNOLOGY = ["ReactJS", "Qwik", "Astro", "SolidJS", "MongoDB", "Java", "Python", "C++", "C#", "C", "PHP", "Swift", "Kotlin", "Go", "Rust", "Dart", "SQL", "NoSQL", "HTML", "CSS", "JavaScript", "TypeScript", "NodeJS", "Angular", "VueJS", "React Native", "Flutter", "Ionic", "Android", "iOS", "AWS"]
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def new
		@project = Project.new
    # @project.project_technologies.build unless @project.project_technologies.any?
	end

  def show

    @project = Project.find(params[:id])
    # Project.where(user: current_user )
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user
    if @project.save
      set_top_picks
       redirect_to project_path(@project)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def project_params
    params.require(:project).permit(:name, :description, :industry, :spoken_language_id, :number_of_developers, technology_ids:[])
  end

  def set_top_picks
    # getting the projects spoken language and all the developers that have the same languages
    @language = @project.spoken_language
    @dev_spoken_langs = DeveloperProfileSpokenLanguage.where(spoken_language: @project.spoken_language)
    @dev_profiles = @dev_spoken_langs.map(&:developer_profile)
    # get t4he prokects all the project tecnologies and then find the developers with the same tecnologies
    @techs = @project.technologies.to_a

    @profiles = @dev_profiles.select do |dev_profile|
      dev_profile.technologies.to_a.intersection(@techs)
    end

    number_of_top_picks = @project.number_of_developers.abs * 3
    @picks = @profiles.first(number_of_top_picks).map do |profile|
      TopPick.create(developer_profile: profile, project: @project)
    end

  end
end

app/views/projects/_project_technology_fields.html.erb
  <div class='nested-fields project_technology_fields'>
      <%= f.input :technology_id %>
      <%= link_to_remove_association "remove project_technologies", f %>
  </div>

app/views/projects/index.html.erb
<h1>Here are your projects</h1>

app/views/projects/new.html.erb
<main class="form--wrapper">
  <h1 class="headline-display">Tell us about your project</h1>
  <!-- this is just to see where this pushes  -->
  <%= simple_form_for(@project) do |f| %>
    <div class ="fieldset">
      <h2 class="form--subtitle">Give us a bit of information on your company</h2>
      <%= f.input :name, label: "Company name"  %>
      <span>Industry</span>
      <div class="dropdown-parent">
        <%= f.select :industry, collection: Project::INDUSTRY%>
      </div>
    </div>
    <div class="fieldset">
      <h2 class="form--subtitle">What is your project about</h2>
      <%= f.input :description, as: :text %>
    </div>
    <div class="fieldset">
      <h2 class="form--subtitle">What kind of profile are you looking for </h2>
      <%= f.association :technologies, input_html: {multiple: true, include_hidden: false }, collection: Technology.all%>
      <%= f.association :spoken_language, collection: SpokenLanguage.all %>
    </div>
    <div class="fieldset">
      <h2 class="form--subtitle">How many developers needed</h2>
      <%= f.input :number_of_developers %>
    </div>
    <%= f.submit %>
  <% end %>
</main>
<style>
  .form--wrapper {
    padding: 24px;
  }
  .fieldset {
    margin-bottom: 60px;
  }
  .form--subtitle {
    font-style: normal;
    font-weight: 500;
    font-size: 32px;
    margin-bottom: 24px;
  }
  .s-form--dropdown {
    display: block;
  }
  .dropdown-parent > select {
    display: block;
    width: 100%;
    padding: 8px 4px;
    height: 38px;
  }
  .form--submit-btn {
    color: var(--on-primary);
  }
  .form--wrapper > input:last-of-type  {
    width: 100%;
    background-color: var(--primary-container);
    color: var(--on-primary);
  }
</style>

app/views/projects/old_new.html.erb
<h1>Tell us about your project</h1>
<main>
  <%= simple_form_for(@project) do |f| %>
    <div class ="fieldset">
      <h2>Give us a bit of information on your company</h2>
      <%= f.input :name, label: "Company name"  %>
      <%= f.select :industry, collection: Project::INDUSTRY %>
    </div>

    <div class="fieldset">
      <h2>What is your project about</h2>
      <%= f.input :description, as: :text %>
    </div>

    <div class="fieldset">
      <h2>How many developers needed</h2>
      <%= f.input :number_of_developers %>
    </div>

    <div class="fieldset">
      <h2>spoken language</h2>
      <% f.input :spoken_language, collection: Project::SPOKEN_LANGUAGE %>
    </div>

    <div class="nested-fields">
      <div class="fieldset">
        <h2>Coding langages and skilled with</h2>
        <%= f.input :project_technologies, collection: Project::TECHNOLOGY%>
      </div>

      <%= f.simple_fields_for :project_technologies do |project_technology| %>
        <%= render 'project_technology_fields', f: project_technology %>
      <% end %>

      <div class="links">
        <%= link_to_add_association 'add technology', f, :project_technologies %>
      </div>
    </div>

    <%= f.submit %>
  <% end %>
</main>

app/views/projects/show.html.erb
<main class="project-section">
  <div class=" card card-wrapper--main">
    <div class="project-title--container">
      <span class="project-subtitle">Project</span>
      <h1 class="project-title"><%= @project.name %></h1>
    </div>
    <span class="project-subtitle">Description</span>
    <p><%= @project.description %></p>
    <div class="inline-flex">
      <div>
        <span class="project-subtitle">Industry</span>
        <p> <%= @project.industry %></p>
      </div>
      <div>
        <span class="project-subtitle">Needs</span>
        <p class="project--subtext">
          <% @project.technologies.each do |technology| %>
            <%= technology.name %>
          <% end %>
        </p>
      </div>
    </div>
  </div>
  <div class=" card card-wrapper--main">
    <div class="">
      <div class="project-title--container">
        <span class="project-subtitle">Recommandations</span>
        <h1 class="project-title">Developer Picks</h1>
      </div>
      <% @project.top_picks.each do |t| %>
        <div class="dev-container">
          <div class="dev-info--container">
            <img src="<%= t.developer_profile.avatar %>" alt="American portrait of developers" class="avatar-img dev-picks--avatar">
            <div class="dev-info--text">
              <h2 class="text--is-primary"><%= t.developer_profile.user.full_name %></h2>
              <p><%= t.developer_profile.description %></p>
            </div>
          </div>
          <div class="dev-profile--btn-container">
            <%= button_to "See profile", developer_path(t.developer_profile), method: :get %>
            <%= button_to "Make an offer", new_developer_offer_path(t.developer_profile), method: :get %>
          </div>
        </div>
        <br>
      <% end %>
    </div>
  </div>
</main>
<style>
  .project-section {
    padding: 24px;
    padding-top: 100px
  }
  .card-wrapper--main {
    padding: 8px;
    margin-bottom: 12px;
  }
  .project-title--container {
    padding-top: 8px;
    border-bottom: var( --stroke);
    margin-bottom: 24px;
  }

  .project-title {
  font-weight: 600;
  font-size: 40px;
  }
  .project-subtitle {
    font-style: normal;
    font-weight: 400;
    font-size: 12px;
    color: var(--txt-secondary);
  }

  .inline-flex {
    display: flex;
    justify-content: space-between;
  }

  .main-btn.full-w {
    display: block;
    width: 100%;
    text-align: center;
  }
  .dev-container {
    padding: 0 16px;
    margin-bottom: 48px;
  }
  .dev-container:last-of-type {
    margin-bottom: 0;
  }
  .dev-info--container {
    display: flex;
    align-items: center;
    justify-content: start;
    margin-bottom: 16px;
  }
  .flex-grow {
    flex-grow: 1;
  }
  .dev-picks--avatar {
    width: 80px;
    margin-right: 12px;
  }
  .mb-24px {
    margin-bottom: 24px;
  }

  .dev-profile--btn-container {
    width: 100%;
    display: flex;
    justify-content: space-between;
    gap: 8px
  }
  .dev-profile--btn-container  > * {
    flex-grow: 1;
  }
   .dev-profile--btn-container  > * > * {
    width: 100%;
  }
</style>