config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :developers, only: [:create, :show, :new, :index] do
    resources :offers, only: [:create, :new]
  end

  resources :projects, only: [:create, :show, :new] do
    resources :offers, only: [:index]
  end

  resources :offers, only: [:update]
  
  resources :chatrooms, only: [:show, :create] do
    resources :messages, only: :create
  end
  
  get "my_dev_profile", to: "developers#my_dev_profile", as: :my_dev_profile
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :project
  belongs_to :developer_profile
  enum status: {
    pending: 0,
    accepted: 1,
    rejected: 2,
  }
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  def new
    @offer = Offer.new
    @developer_profile = DeveloperProfile.find(params[:developer_id])
    @developer_technologies = @developer_profile.technologies
    @user = @developer_profile.user
  end

  def show
    @offer = Offer.find(params[:id])
    @offer.user = current_user
  end

  def create
    @developer_profile = DeveloperProfile.find(params[:developer_id])
    @offer = Offer.new(offer_params)
    @offer.developer_profile = @developer_profile
    @offer.project = current_user.projects.last
    if @offer.save

      redirect_to project_offers_path(@offer.project)
    else

      render :new, status: :unprocessable_entity
    end
  end

  def update
    @offer = Offer.find(params[:id])
    @offer.update(offer_params)
    redirect_to project_path(@offer.project)
  end

  def index
    @offers = current_user.projects.last.offers

  end

  private

  def offer_params
    params.require(:offer).permit(:houry_rate, :Number_of_hours,:status, :project_id)
  end
end

app/views/offers/index.html.erb
<main class="offer-status--wrapper">
  <h1 class="headline-display">Offer Statuses</h1>
  <% @offers.each do |offer|%>
    <div class="card offer--status-card--wrapper">
      <div class="offer--dev--wrapper">
        <div class="space-between">
          <img src="<%= offer.developer_profile.avatar %>" alt="A american portrait of a developer" class="avatar-img mb-24">
          <div class="offer--dev-title--container">
            <h3 class="text--is-primary"><%= offer.developer_profile.user.full_name %></h3>
            <p><%= offer.developer_profile.description %></p>
          </div>
        </div>
        <div class="space-between align-right">
          <div class="status-chip <%= offer.status %>">
            <i class="status-chip--decarator"></i>
            <span>Offer <%= offer.status.capitalize %></span>
          </div>
          <%= link_to "See Profile" ,developer_path(offer.developer_profile), class: "btn-secondary"  %>
        </div>
      </div>
    </div>
  <% end %>
</main>
<style>
  p {
    margin-bottom: 0;
  }
  .offer-status--wrapper {
    padding: 0 24px;
  }
  .offer--dev--wrapper {
    display: flex;
    justify-content: space-between;
  }
  .space-between {
    display: flex;
    flex-direction: column;
    justify-content: space-between;
  }
  .align-right {
    align-items: flex-end;
    flex-shrink: 0;
  }
  .card.offer--status-card--wrapper {
    padding:24px 12px;
  }
  /* START of status chip */
  .status-chip {
    display: flex;
    flex-direction: row;
    align-items: center;
    padding: 8px 16px 8px 8px;
    gap: 6px;
    border-radius: 100vw;
  }

  .status-chip.pending {
    background: hsla(60, 22%, 86%, 1);
  }
  .status-chip.accepted {
    background: rgba(216, 237, 124, 0.7);
  }

  .status-chip.rejected {
    background: hsla(6, 100%, 92%, 1);
  }

  .status-chip .status-chip--decarator {
    width: 8px;
    height: 8px;
    border-radius: 1vw;
    background: #46483C;
  }
  .status-chip.pending  .status-chip--decarator {
    background: #46483C;
  }
   .status-chip.pending  span{
    color: #46483C;
  }

  .status-chip.accepted .status-chip--decarator {
    color: hsla(69, 100%, 15%, 1);
  }

  .status-chip.accepted span {
    color: hsla(69, 100%, 15%, 1);
  ;
  }
  .status-chip.rejected .status-chip--decarator {
    background:#410002;
  }
  .status-chip.rejected span {
    color:#410002;
  }
  /* END of status chip */
  .btn-secondary {
    text-decoration: none;
    background-color: var(--secondary-container);
    color: var(--on-secondary);
    border-radius: 4px;
    padding: 8px 16px;
  }
</style>

app/views/offers/new.html.erb
<main class="offer-wrapper">
  <h1 class="headline-display">Make an offer</h1>
  <div class="card dev-profile--info-wrapper">
    <div class="dev-profile--info-container">
      <div class="gradiented-card-cover">
      </div>
      <img src="<%= @developer_profile.avatar %>" alt="A american portrait of a developer" class="avatar-img mt-20">
      <h2 class="text--is-primary">
        <%= @user.full_name %>
      </h2>
      <span> <%= @developer_profile.description %></span>
    </div>
  </div>
  <div class="card card-wrapper--main">
    <div class="offer-form--container">
      <%# TODO: make sure it sends the form submission to offer %>
      <%= simple_form_for([@developer_profile, @offer], url: developer_offers_path(@developer_profile)) do |f| %>
        <p class = "number-field--label">Number of hours</p>
        <%= f.number_field :Number_of_hours %>
        <p class ="number-field--label">Hourly Rate</p>
        <%= f.number_field :hourly_rate %>
        <%# TODO: Add custom label %>
        <%= f.submit %>
      <% end %>
    </div>
  </div>
</main>
<style>
  .offer-form--container input[type=submit] {
    margin-top: 32px;
  }
    .offer-wrapper {
      padding: 0 24px;
      padding-bottom: 24px;
    }
    .offer-wrapper input[type="submit"] {
      border-radius: 8px;
    }
    .number-field--label {
      font-size: 14px;
      font-weight: 450;
      color: #404C00;
      margin-bottom: 8px;
    }
    .number-field--label:last-of-type {
      margin-top: 16px;
    }
</style>